# Generated by Django 5.2.17 on 2026-09-19 05:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Nomi')),
                ('issuer', models.CharField(blank=True, max_length=140, verbose_name='Beruvchi')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Sana')),
                ('url', models.URLField(blank=True, verbose_name='Havola')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Yutuq / sertifikat',
                'verbose_name_plural': 'Yutuqlar va sertifikatlar',
                'ordering': ('order', '-date'),
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Boshlanish')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash')),
                ('is_current', models.BooleanField(default=False, verbose_name='Hozir davom etmoqda')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('degree', models.CharField(max_length=140, verbose_name="Yo'nalish / daraja")),
                ('institution', models.CharField(max_length=140, verbose_name="O'quv muassasasi")),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='Manzil')),
                ('description', models.TextField(blank=True, help_text='Boy matn.', verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': "Ta'lim",
                'verbose_name_plural': "Ta'lim",
                'ordering': ('order', '-start_date'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Boshlanish')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash')),
                ('is_current', models.BooleanField(default=False, verbose_name='Hozir davom etmoqda')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('role', models.CharField(max_length=140, verbose_name='Lavozim')),
                ('company', models.CharField(max_length=140, verbose_name='Tashkilot')),
                ('company_url', models.URLField(blank=True, verbose_name='Tashkilot sayti')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='Manzil')),
                ('description', models.TextField(blank=True, help_text='Boy matn.', verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Tajriba',
                'verbose_name_plural': 'Ish tajribasi',
                'ordering': ('order', '-start_date'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LanguageSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Til')),
                ('level', models.CharField(blank=True, max_length=60, verbose_name='Daraja')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Til',
                'verbose_name_plural': 'Tillar',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, verbose_name='E-pochta')),
                ('subject', models.CharField(blank=True, max_length=160, verbose_name='Mavzu')),
                ('body', models.TextField(verbose_name='Xabar')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Ismingiz Familiyangiz', max_length=120, verbose_name="To'liq ism")),
                ('headline', models.CharField(blank=True, max_length=160, verbose_name='Kasb / lavozim')),
                ('tagline', models.CharField(blank=True, help_text='Bosh sahifadagi sarlavha ostida chiqadi.', max_length=240, verbose_name='Qisqa shior')),
                ('about', models.TextField(blank=True, help_text="Boy matn (rich text) qo'llab-quvvatlanadi.", verbose_name='Men haqimda')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='Manzil')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-pochta')),
                ('phone', models.CharField(blank=True, max_length=60, verbose_name='Telefon')),
                ('website', models.URLField(blank=True, verbose_name='Sayt')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Surat')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resume/', verbose_name='Rezyume fayli (PDF)')),
                ('available_for_work', models.BooleanField(default=True, verbose_name='Ish takliflariga ochiqman')),
                ('masthead', models.CharField(blank=True, help_text="Sahifa tepasidagi katta sarlavha. Bo'sh bo'lsa ism ishlatiladi.", max_length=80, verbose_name='Gazeta nomi')),
                ('edition_note', models.CharField(blank=True, help_text='Masalan: “Mustaqil nashr · Toshkent”.', max_length=120, verbose_name='Nashr izohi')),
                ('footer_note', models.CharField(blank=True, max_length=200, verbose_name='Pastki izoh')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profil',
            },
        ),
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Guruh nomi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': "Ko'nikma guruhi",
                'verbose_name_plural': "Ko'nikma guruhlari",
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60, verbose_name='Nomi')),
                ('url', models.URLField(verbose_name='Havola')),
                ('handle', models.CharField(blank=True, max_length=80, verbose_name='Foydalanuvchi nomi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Ijtimoiy havola',
                'verbose_name_plural': 'Ijtimoiy havolalar',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name="Ko'nikma")),
                ('note', models.CharField(blank=True, max_length=80, verbose_name='Izoh')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.skillgroup', verbose_name='Guruh')),
            ],
            options={
                'verbose_name': "Ko'nikma",
                'verbose_name_plural': "Ko'nikmalar",
                'ordering': ('order', 'id'),
            },
        ),
    ]
