# Generated by Django 5.2.17 on 2026-09-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(blank=True, max_length=220, verbose_name="Qo'shimcha matn")),
                ('image', models.ImageField(upload_to='slider/', verbose_name='Rasm')),
                ('url', models.CharField(blank=True, help_text="To'liq manzil (https://…) yoki sayt ichidagi yo'l (/portfolio/).", max_length=300, verbose_name='Havola')),
                ('link_label', models.CharField(blank=True, help_text="Bo'sh qoldirsangiz “Batafsil” yoziladi.", max_length=60, verbose_name='Havola matni')),
                ('is_active', models.BooleanField(default=True, verbose_name="Ko'rsatilsin")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Slayder elementi',
                'verbose_name_plural': 'Slayder',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='edition_note',
            field=models.CharField(blank=True, help_text='Sahifa tepasida, sana yonida chiqadi. Masalan: “Toshkent”.', max_length=120, verbose_name='Sarlavha yonidagi izoh'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='masthead',
            field=models.CharField(blank=True, help_text="Sahifa tepasidagi katta sarlavha. Bo'sh bo'lsa ism ishlatiladi.", max_length=80, verbose_name='Sayt nomi'),
        ),
    ]
