# Generated by Django 5.2.17 on 2026-09-19 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_slideitem_alter_profile_edition_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideitem',
            name='blur_width',
            field=models.PositiveSmallIntegerField(default=52, help_text='Rasmning necha foizi xiralashsin — qolgani ravshan qoladi.', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(100)], verbose_name='Xira maydon kengligi (%)'),
        ),
        migrations.AddField(
            model_name='slideitem',
            name='image_blur',
            field=models.PositiveSmallIntegerField(default=12, help_text='0 — rasm xiralashtirilmaydi.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)], verbose_name='Rasmning shu tomonidagi xiralik'),
        ),
        migrations.AddField(
            model_name='slideitem',
            name='panel_blur',
            field=models.PositiveSmallIntegerField(default=16, help_text="0 — shaffof shisha effekti o'chadi. Odatda 12–20 px yaxshi chiqadi.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)], verbose_name='Karta ortidagi xiralik'),
        ),
        migrations.AddField(
            model_name='slideitem',
            name='panel_style',
            field=models.CharField(choices=[('glass', "Shaffof shisha — yorug'"), ('glass-dark', "Shaffof shisha — to'q"), ('paper', "Oddiy qog'oz (shaffofsiz)")], default='glass', max_length=12, verbose_name='Karta uslubi'),
        ),
        migrations.AddField(
            model_name='slideitem',
            name='side',
            field=models.CharField(choices=[('left', 'Chap tomon'), ('right', "O'ng tomon")], default='left', help_text='Sarlavha kartasi rasmning qaysi tomonida tursin.', max_length=10, verbose_name='Karta tomoni'),
        ),
    ]
