# Generated by Django 5.2.17 on 2026-09-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_xabar_bog_lanish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(max_length=500, verbose_name='Xabar'),
        ),
    ]
