# Generated by Django 5.2.17 on 2026-09-19 05:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('rubric', models.CharField(blank=True, help_text='Masalan: Texnologiya, Dizayn, Kundalik.', max_length=60, verbose_name='Rubrika')),
                ('lead', models.CharField(blank=True, help_text="Sarlavha ostidagi bir-ikki gap; ro'yxatlarda ham ko'rinadi.", max_length=300, verbose_name='Lid')),
                ('body', models.TextField(blank=True, help_text='Boy matn muharriri.', verbose_name='Maqola matni')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Muqova rasm')),
                ('cover_caption', models.CharField(blank=True, max_length=200, verbose_name='Rasm izohi')),
                ('published_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Nashr sanasi')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chop etilgan')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Bosh sahifada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
                'ordering': ('-published_at', '-created_at'),
            },
        ),
    ]
