# Generated by Django 5.2.17 on 2026-09-19 05:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name="Saytda ko'rinsin"),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Sana'),
        ),
    ]
