# Generated by Django 5.2.17 on 2026-09-19 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Papka nomi')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='Qisqa tavsif')),
                ('tone', models.CharField(choices=[('manila', 'Manila (odatiy)'), ('sand', 'Qum'), ('sage', 'Zaytun'), ('blush', 'Pushti'), ('slate', "Ko'k-kulrang")], default='manila', max_length=20, verbose_name='Rang')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='folders/', verbose_name='Muqova rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Papka',
                'verbose_name_plural': 'Papkalar',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Sarlavha')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('summary', models.CharField(blank=True, help_text="Ro'yxatlarda ko'rinadigan bir-ikki gap.", max_length=300, verbose_name='Qisqacha')),
                ('body', models.TextField(blank=True, help_text="Boy matn muharriri: sarlavha, ro'yxat, rasm, kod, iqtibos.", verbose_name="To'liq tavsif")),
                ('cover', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Muqova rasm')),
                ('role', models.CharField(blank=True, max_length=140, verbose_name='Mening rolim')),
                ('client', models.CharField(blank=True, max_length=140, verbose_name='Buyurtmachi / jamoa')),
                ('tech', models.CharField(blank=True, help_text='Vergul bilan ajrating: Django, PostgreSQL, Figma', max_length=240, verbose_name='Texnologiyalar')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yil')),
                ('status', models.CharField(choices=[('done', 'Yakunlangan'), ('ongoing', 'Davom etmoqda'), ('concept', 'Konsept'), ('archived', 'Arxiv')], default='done', max_length=20, verbose_name='Holat')),
                ('live_url', models.URLField(blank=True, verbose_name='Jonli havola')),
                ('repo_url', models.URLField(blank=True, verbose_name='Kod havolasi')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Bosh sahifada')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chop etilgan')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='portfolio.folder', verbose_name='Papka')),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
                'ordering': ('order', '-year', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/', verbose_name='Rasm')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project', verbose_name='Loyiha')),
            ],
            options={
                'verbose_name': 'Loyiha rasmi',
                'verbose_name_plural': 'Loyiha rasmlari',
                'ordering': ('order', 'id'),
            },
        ),
    ]
