# Generated by Django 5.2.17 on 2026-09-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name="Saytda ko'rinsin"),
        ),
    ]
